server:
  port: 8093

spring:
  application:
    name: xht-activiti

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.213.134:3306/xht_back?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yzd2021$$

  data:
    redis:
      host: 192.168.213.134
      port: 6379
      password: yzd2021$$

  activiti:
    db-history-used: true
    history-level: full
    database-schema-update: true
    check-process-definitions: false
    deployment-mode: never-fail

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.213.134:8848

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  config-location: classpath:/mybatis-config.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted #默认deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto



