server:
  port: 8091
  servlet:
    context-path: /oauth

spring:
  application:
    name: xht-oauth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.213.134:3306/xht_back?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yzd2021$$

  data:
    redis:
      host: 192.168.213.134
      port: 6379
      password: yzd2021$$


  cloud:
    nacos:
      discovery:
        server-addr: 192.168.213.134:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted #默认deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oauth:
  login-url: /login
  logout-url: /logout

